server:
  port: 8160
spring:
  application:
    name: mall-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ums?serverTimezone=UTC
    username: root
    password: kevintam
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis

aliyun:
  accessKeyId: LTAI5tDYRa5DdiwPRvJM1JTv
  accessKeySecret: pMPKBiVucfZu5R3ylnVjtmI261lGQE
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback

management:
  endpoints:
    web:
      exposure:
        include: '*'