server:
  port: 8005
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mall_wms?serverTimeZone=UTC
    password: kevintam
  application:
    name: mall-ware
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
