server:
  port: 8600
spring:
  application:
    name: mall-cart-service
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ums?serverTimezone=UTC
    username: root
    password: kevintam
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  session:
    store-type: redis