spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_pms?serverTimezone=UTC
    username: root
    password: kevintam
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: 
      oss:
        endpoint: 
  profiles:
    active: dev
  application:
    name: mall-product
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
      #最大连接数，默认8
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  cache:
    type: redis #配置什么来缓存
    redis:
      time-to-live: 600000  #redis的key的存活时间，单位是秒
      key-prefix: CACHE_ #key的前缀
      use-key-prefix: true #是否使用前缀
      cache-null-values: true #是否缓存空值
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
server:
  port: 9001
logging:
  level:
    com.serookie.product: debug
#日志
