server:
  port: 1000
spring:
  application:
    name: elasticsearch-service
  datasource:
    url: jdbc:mysql://localhost:3306/mall_pms?serverTimezone=UTC
    username: root
    password: kevintam
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false

